---
title: "Classe 0 - Introducció"
author: "Eudald Correig"
date: "Juny 2019"
output: ioslides_presentation
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

## Introducció

- Curs nivell mitjà d'R continuació del d'iniciació

- Repàs i continuació del curs bàsic

- Totalment pràctic

- Amb les vostres bases de dades

Requisits:

- Coneixement bàsic d'R

Recomanacions:

- Coneixement bàsic d'estadística

## Organització

1. Repàs introducció a R: instal·lació, utilització d'RStudio i Markdown.
1. Importació de fitxers: csv, excels, spss, etc.
1. Manipulació bàsica de dades.
1. Iteracions: loops i condicionals.
1. Tractament de "missings".
1. **Manipulació de dades nivell mitjà**: comandes "melt", "cast" i "reshape".
1. Anàlisis estadístics nivel mitjà: proves d'hipòtesi i regressions lineals i logístiques.
1. Elaboració de gràfics: ggplot2
1. Elaboració d'informes: Markdown nivell mitjà.
1. Creació d'Scripts (opcional)

## Objectius

- Manipular les vostres pròpies bases de dades
- Fer anàlisis *simples* exploratoris
- Preparar visualitzacions dels resultats

## Recursos

Podeu trobar aquest curs a: 

https://github.com/ecorreig/curs-r-nivell-mig

Altres fonts d'informació:

https://itsalocke.com/files/DataManipulationinR.pdf

https://data-flair.training/blogs/data-manipulation-in-r/

Avançat:

https://www.datacamp.com/courses/dplyr-data-manipulation-r-tutorial

https://www.datasciencecentral.com/profiles/blogs/exclusive-tutorial-on-data-manipulation-with-r-50-examples

## Obtenir informació i ajuda

Llocs on treure informació sobre llibreries, tutorials o demanar ajuda:

**Tutorials**: https://www.statmethods.net/index.html, https://www.r-bloggers.com

**Documentació**: https://cran.r-project.org/manuals.html

**LLibreries** (exemple): https://cran.r-project.org/web/packages/lme4/lme4.pdf

**Demanar ajuda**: https://stackoverflow.com (prgramar)

**Demanar ajuda**: https://stats.stackexchange.com/ (estadística)

Per qualsevol altra cosa, google.